---
pipeline:
  drone_s3_cache_pull:
     image: quay.io/ukhomeofficedigital/drone-s3cache:v0.1.0
     drone_s3_cache_mode: "pull"

  build:
    commands:
       - mvn clean install
    environment:
       - BUILD_NUMBER=${DRONE_BUILD_NUMBER}
    image: "quay.io/ukhomeofficedigital/java8-mvn:v3.3.9"
    when:
      event:
        - push

  drone_s3_cache_push:
    image: quay.io/ukhomeofficedigital/drone-s3cache:v0.1.0
    drone_s3_cache_folders:
      - .m2
    drone_s3_cache_mode: "push"

  build_image:
    commands:
      - "docker build --label ${DRONE_BUILD_NUMBER} --build-arg BUILD_NUMBER=${DRONE_BUILD_NUMBER} -t rest-experian-qas-internet ."
    environment:
      - "DOCKER_HOST=tcp://127.0.0.1:2375"
    image: docker:1.11
    when:
      branch: master
      event: push

  image_to_quay:
    commands:
      - "docker login -u=\"ukhomeofficedigital+drone\" -p=${DOCKER_PASSWORD} quay.io"
      - "docker tag rest-experian-qas-internet quay.io/ukhomeofficedigital/rest-experian-qas-internet:${DRONE_COMMIT_SHA}"
      - "docker push quay.io/ukhomeofficedigital/rest-experian-qas-internet:${DRONE_COMMIT_SHA}"
    environment:
      - "DOCKER_HOST=tcp://127.0.0.1:2375"
    image: docker:1.11
    when:
      branch: master
      event: push

  # trigger_deploy_to_dev:
  #   commands:
  #     - "kd --insecure-skip-tls-verify --retries 30 -f kube/config/${KUBE_NAMESPACE}.yaml -f kube/rest-experian-qas-internet-dev-dp.yaml -f kube/rest-experian-qas-internet-dev-svc.yaml -f kube/rest-experian-qas-internet-dev-ingress.yaml"
  #   environment:
  #     - "KUBE_NAMESPACE=rest-experian-qas-internet-dev"
  #     - "KUBE_SERVER=https://kube-dev.dsp.notprod.homeoffice.gov.uk"
  #     - "INSECURE_SKIP_TLS_VERIFY=true"
  #   image: quay.io/ukhomeofficedigital/kd:v0.2.2
  #   when:
  #     branch: master
  #     event: push

services:
  dind:
    command:
      - "-s"
      - overlay
    image: docker:1.11-dind
    privileged: true
